controller_manager:
  ros__parameters:
    update_rate: 20  # Hz
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    omni_wheel_drive_controller:
      type: omni_wheel_drive_controller/OmniWheelDriveController

omni_wheel_drive_controller:
  ros__parameters:
    type: omni_wheel_drive_controller/OmniWheelDriveController
    wheel_names: 
      - wheel0_joint
      - wheel1_joint
      - wheel2_joint
      - wheel3_joint
    wheel_offset: 0.0
    robot_radius: 0.085
    wheel_radius: 0.0508

    publish_rate: 20.0
    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal : [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]
    twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.001, 0.001, 0.01]

    open_loop: false
    position_feedback: true
    enable_odom_tf: true

    cmd_vel_timeout: 0.5
    use_stamped_vel: true

arm_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - Revolute 1
      - Revolute 2
      - Revolute 3
      - Revolute 4
      - Revolute 5
      - Revolute 6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
